apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: game
  name: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AdarshBarbate/k8s-gitops.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: game